### ISSUE TITLE
Is it possible to add a comment to a calendar_event?

### ISSUE THREAD

**Issue by ca-dsgn** [basecamp/bcx-api#227] opened 2019-06-26 07:27 UTC
Hi guys,

I tried to create a comment via your API on a calendar event, but this doesn't seem to work:

https://basecamp.com/<account_id>/api/v1/calendars/<calendar_id>/calendar_events/<calendar_event_id>/comments.json

Using this JSON:
`{
  "content": "Hi there",
  "attachments": [
    {
      "token": "5f6562ea-97e3-11e9-912f-a0369f35eed4",
      "name:": "meta.txt"
    },
    {
      "token": "603b4298-97e3-11e9-8573-a0369f35eeca",
      "name:": "email.html"
    }
  ]
}`

The file attachement worked perfectly and returned the tokens in the JSON (see on top).

Am I doing something wrong or why is the comment creation not working?

Thank you for your help.

Christian

**Comment by rosa** [comment] 2019-06-26 07:55
Hi @ca-dsgn! It's possible to add comments to calendar events for events in project calendars only. The URL to which you should post the comment would be: 
```
https://basecamp.com/<account_id>/api/v1/projects/<project_id>/calendar_events/<calendar_event_id>/comments.json
```
Adding comments to calendar events in calendars that are independent of projects is not possible via the API.

**Comment by ca-dsgn** [comment] 2019-06-26 13:09
Thanks @rosa for the quick reply on this. Is there any other possibility to add an attachment to a calendar based calendar event via api?

**Comment by rosa** [comment] 2019-06-26 14:35
I'm afraid not 😞 Attachments can only be attached to messages, to-dos, uploads and comments, and comments can't be created via the API for calendar-based calendar events. In any case, let me look into it, it's possible we can add support for posting comments to calendar events that belong to independent calendars.

**Comment by ca-dsgn** [comment] 2019-06-27 08:17
@rosa Thank you very much for looking into it. It would be great if you can add support for posting comments to independent calendar events.

**Comment by rosa** [comment] 2019-06-27 15:17
@ca-dsgn it seemed like not supporting comments in events belonging to calendars was an oversight, I just pushed a fix for this, so that posting the comment (with or without attachments) to `https://basecamp.com/<account_id>/api/v1/calendars/<calendar_id>/calendar_events/<calendar_event_id>/comments.json` should work now. Could you give it a try?

**Comment by ca-dsgn** [comment] 2019-06-28 06:57
Hi @rosa, the response looks much better now (I get a response now) but I got this error:

`{"attachments":["is invalid","is invalid"]}`

I also tried without the attachments and this worked - I got this response:

` {"id":707382868,"content":"Hi there","created_at":"2019-06-28T08:54:11.020+02:00","updated_at":"2019-06-28T08:54:11.020+02:00","private":false,"trashed":false,"attachments":[],"creator":{"id":15802243,"name":"Christian Albert","avatar_url":"http:\\/\\/cdn.37img.com\\/builtin\\/default_avatar_v1_3\\/avatar.gif?r=3","fullsize_avatar_url":"https:\\/\\/cdn.37img.com\\/builtin\\/default_avatar_v1_3\\/original.gif?r=3"},"topic_url":"https:\\/\\/basecamp.com\\/2014486\\/api\\/v1\\/calendars\\/1587279\\/calendar_events\\/40266182.json","topic_app_url":"https:\\/\\/basecamp.com\\/2014486\\/calendars\\/1587279\\/calendar_events\\/40266182"}`

The request with the attachments looks like this:

`{  "content": "Hi there",  "new_subscriber_emails": ["example@example.com"],  "attachments": [  {"token": "c88e3924-9971-11e9-82ce-a0369f35eed4","name:": "meta.txt"},{"token": "c952983c-9971-11e9-b75a-a0369f35eeca","name:": "email.html"}  ]}`

The tokens are always freshly created (via https://basecamp.com/2014486/api/v1/attachments.json). Is there a problem with the name?

Thank you very much for your support on this.

**Comment by rosa** [comment] 2019-06-29 05:13
Oh! I had another look and I believe we have yet another bug around posting comments via the API that is causing this error. I'll work on fixing it, sorry about that!

**Comment by ca-dsgn** [comment] 2019-07-02 11:12
Hi @rosa, no worries - I am happy that you are supporting me on this. Any updates on the fix yet? Thank you.

**Comment by rosa** [comment] 2019-07-02 11:27
Thanks for your understanding! I believe I found the root cause but didn't have enough time yesterday to confirm it and work on a fix. I hope to have time today 🤞

**Comment by rosa** [comment] 2019-07-03 08:38
Hey @ca-dsgn, this should be fixed now. I verified that I can successfully create comments in a calendar event that belongs to a calendar with attachments. Could you give it a try? If it doesn't work, we'll troubleshoot your particular case.

**Comment by ca-dsgn** [comment] 2019-07-03 15:47
Hi @rosa,

thank you for coming back to this issue so quick.

I tested again but unfortunately I is not working yet.

When doing this call:
`https://basecamp.com/<account_id>/api/v1/projects/<project_id>/calendar_events/<calendar_event_id>/comments.json`

Using this JSON:

`{  "content": "Hi there",  "new_subscriber_emails": ["example@example.com"],  "attachments": [  {"token": "035476be-9da9-11e9-887c-a0369f35eed4","name:": "meta.txt"},{"token": "04237b94-9da9-11e9-a2b6-a0369f35eeca","name:": "email.html"}  ]}`

I get this response:
`{"attachments":["is invalid","is invalid"]}`

The used tokens in this call I successfully received from two earlier calls using

`https://basecamp.com/2014486/api/v1/attachments.json`

My assumption is that there is a problem with the JSON in the call token or name. Do you have any idea?

Thank you.

**Comment by rosa** [comment] 2019-07-03 16:14
Strange! 😕 Your JSON request body looks fine to me, including the tokens and the names for the attachments (they don't have to match the names of the files posted to `/attachments.json`). I'll dig a bit more to see if I can figure out what's going on!

**Comment by rosa** [comment] 2019-07-03 16:26
Ooooh, I just saw it! 😅 It's the silliest typo, and it took me a lot of looking at logs to see it, lol, it's the `name` parameter, it's being submitted as `name:`, with an extra `:`. 
```
"name:": "meta.txt"
```
Should be:
```
"name": "meta.txt"
```
I hope it does work now!

**Comment by ca-dsgn** [comment] 2019-07-03 17:16
Ahhh, my bad @rosa! Now it works!! Thank you so much for your help and your great support!

**Comment by rosa** [comment] 2019-07-03 17:28
Nice! 👏👏

**Closed by rosa** 2019-07-03 17:28 UTC
